### ISSUE TITLE
Compatibility with Grunt ~1.0.0

### ISSUE THREAD

**Issue by swissspidy** [stephenharris/grunt-checktextdomain#10]
The package currently states that it requires Grunt ~0.4.1. Most of the packages that are being used in combination (at least in our case), require Grunt ~1.0.0. I don't see a reason grunt-checktextdomain shouldn't work with that.

Any more info on this? Perhaps the requirement could be made less strict, i.e. require 0.4.1 _or greater_.

**Comment by stephenharris** [comment]
I think this was fixed with 1.0.1? https://github.com/stephenharris/grunt-checktextdomain/commit/c3480a7e56b163dc0ec7e0d509e30451a2265be3

I haven't tagged that here, but should it should be published on npm

**Comment by swissspidy** [comment]
Huh, strange, then it must have been something else. Completely removed all node modules and installed again. Works fine.

Worth noting that the readme needs to be adjusted though.

Thanks for taking your time!
