### ISSUE TITLE
_n not working as intended

### ISSUE THREAD

**Issue by vpratfr** [stephenharris/grunt-checktextdomain#7]
I get that warning: 

```
[L699]  _n  Variable used in domain argument
```

And the corresponding line:

```
                $errors[] = sprintf(
                    _n(
                        'You are not allowed to attach more than %d file',
                        'You are not allowed to attach more than %d files',
                        $max_file_count,
                        'cuar'),
                    $max_file_count);
```

And then `$max_file_count` gets replaced by `'cuar'`

Any idea of why the plural does not get handled properly?

**Comment by stephenharris** [comment]
Haven't had chance to test the example yet, but what is your Gruntfile configuration for the task?

**Comment by vpratfr** [comment]
That was the issue. Copied the configuration from the README and it works now. 

Thanks :)
